@startuml Cliente
!startsub Cliente
skinparam ClassAttributeIconSize 0

class cliente {
    - dinero: float
    - permiso : Permiso
    - venta : Venta
    + actualizar() : void
    + actualizarDinero(float) : void
    + actualizarPermiso( Permiso ) : void
    + eliminarDatos() : void
}

@enduml
!endsub
