@startuml Proveedor
!startsub Proveedor
skinparam ClassAttributeIconSize 0

class proveedor {
    - dinero: float
    - permiso: Permiso
    - compra: Compra
    + actualizar() : void
    + actualizarPermiso( Permiso ) : void
    + eliminarDatos() : void
}

@enduml
!endsub
