@startuml Persona
!startsub Persona
skinparam ClassAttributeIconSize 0

class persona{
    - name: String
    - email: String
    - edad: int
    + actualizarPerfil(String, String, int): void
}

!endsub
@enduml
