@startuml Stock
!startsub Stock
skinparam ClassAttributeIconSize 0

class stock{
    -idStock: String
    - precioTotal: float
    - precio : float
    - cantidadEnStock: int
    - empresa: Empresa
    + incrementarStock(int): void
    + decrementarStock(int): void
    + verificarNivelStock(): int
    + actualizarPrecio(float): void
}

!endsub
@startuml
